# Generated by Django 5.0.6 on 2024-05-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
